# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-07 00:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('datapoint', '0001_initial'), ('datapoint', '0002_auto_20160203_1929'), ('datapoint', '0003_auto_20160203_1943'), ('datapoint', '0004_auto_20160207_0046')]

    initial = True

    dependencies = [
        ('device', '0001_squashed_0005_auto_20160207_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.IntegerField()),
                ('type', models.CharField(blank=True, max_length=50)),
                ('extra', models.TextField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_lat', models.DecimalField(decimal_places=9, max_digits=12, verbose_name='Latitude')),
                ('_lng', models.DecimalField(decimal_places=9, max_digits=12, verbose_name='Longitude')),
            ],
        ),
        migrations.AddField(
            model_name='datapoint',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datapoint.Point'),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='collected_at',
            field=models.DateTimeField(verbose_name='Collected at'),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='extra',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Added at'),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='data',
            field=models.IntegerField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='extra',
            field=models.TextField(blank=True, verbose_name='Extra'),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Type'),
        ),
    ]
