# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datapoint', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_lat', models.DecimalField(decimal_places=9, max_digits=12)),
                ('_lng', models.DecimalField(decimal_places=9, max_digits=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='datapoint',
            name='_lat',
        ),
        migrations.RemoveField(
            model_name='datapoint',
            name='_lng',
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datapoint.Point'),
        ),
    ]
