# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 19:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('datapoint', '0002_auto_20160203_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='collected_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 3, 19, 43, 23, 995365, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='extra',
            field=models.TextField(blank=True),
        ),
    ]
