# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-07 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapoint', '0003_auto_20160203_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Added at'),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='collected_at',
            field=models.DateTimeField(verbose_name='Collected at'),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='data',
            field=models.IntegerField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='extra',
            field=models.TextField(blank=True, verbose_name='Extra'),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='point',
            name='_lat',
            field=models.DecimalField(decimal_places=9, max_digits=12, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='point',
            name='_lng',
            field=models.DecimalField(decimal_places=9, max_digits=12, verbose_name='Longitude'),
        ),
    ]
