# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-07 00:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('device', '0001_initial'), ('device', '0002_remove_device_updated_at'), ('device', '0003_device_token'), ('device', '0004_auto_20160131_0212'), ('device', '0005_auto_20160207_0046')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Added at')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token')),
                ('public', models.BooleanField(default=False, verbose_name='Public')),
            ],
        ),
    ]
