# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_device_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
