# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-07 00:46
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_auto_20160131_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Public'),
        ),
        migrations.AlterField(
            model_name='device',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Added at'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='device',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token'),
        ),
    ]
